# .pages.yml — Pages CMS config (all images in src/images)

media:
  name: images
  label: Images
  input: src/images
  output: src/images
  path: ""
  extensions: [png, jpg, jpeg, webp, svg]

settings:
  content:
    merge: true

content:
  # WORK
  - name: work
    label: Work
    type: collection
    path: src/content/work
    filename: "{year}{month}{day}-{hour}{minute}{second}.md"
    view:
      primary: title
      fields: [title, pubDate, subtitle]
      sort: [pubDate]
      default:
        sort: pubDate
        order: desc
    fields:
      - { name: pubDate,  label: Pub Date,  type: date }
      - { name: title,    label: Title,     type: string, required: true }
      - { name: subtitle, label: Subtitle,  type: string }
      - { name: live,     label: Live URL,  type: string }
      - name: image
        label: Image
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images } }
          - { name: alt, label: Alt text, type: string }
      - { name: body, label: Body, type: rich-text }

  # STORE
  - name: store
    label: Store
    type: collection
    path: src/content/store
    filename: "{year}{month}{day}-{hour}{minute}{second}.md"
    view:
      primary: title
      fields: [title, price]
      sort: [title]
    fields:
      - { name: price,     label: Price,       type: string }
      - { name: title,     label: Title,       type: string, required: true }
      - { name: preview,   label: Preview URL, type: string }
      - { name: checkout,  label: Checkout URL,type: string }
      - { name: license,   label: License,     type: string }
      - name: highlights
        label: Highlights
        type: string
        list: true
      - { name: description, label: Description, type: text }
      - name: features
        label: Features
        type: object
        list: true
        fields:
          - { name: title,       label: Title,       type: string }
          - { name: description, label: Description, type: text }
      - name: image
        label: Main Image
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images } }
          - { name: alt, label: Alt text, type: string }
      - name: images
        label: Gallery
        type: object
        list: true
        fields:
          - { name: url, label: Image, type: image, options: { media: images } }
          - { name: alt, label: Alt text, type: string }
      - { name: body, label: Body, type: rich-text }

  # PROJECTS
  - name: projects
    label: Projects
    type: collection
    path: src/content/projects
    filename: "{year}{month}{day}-{hour}{minute}{second}.md"
    view:
      primary: title
      fields: [title, pubDate, subtitle]
      sort: [pubDate]
      default:
        sort: pubDate
        order: desc
    fields:
      - { name: pubDate,  label: Pub Date, type: date }
      - { name: title,    label: Title,    type: string, required: true }
      - { name: subtitle, label: Subtitle, type: string }
      - { name: live,     label: Live URL, type: string }
      - name: logo
        label: Logo
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images } }
          - { name: alt, label: Alt text, type: string }
      - name: image
        label: Cover/Image
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images } }
          - { name: alt, label: Alt text, type: string }
      - { name: body, label: Body, type: rich-text }

  # POSTS
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    filename: "{year}{month}{day}-{hour}{minute}{second}.md"
    view:
      primary: title
      fields: [title, pubDate, author]
      sort: [pubDate]
      default:
        sort: pubDate
        order: desc
    fields:
      - { name: title,       label: Title,       type: string, required: true }
      - { name: pubDate,     label: Pub Date,    type: date }
      - { name: description, label: Description, type: text }
      - { name: author,      label: Author,      type: string }
      - name: image
        label: Cover Image
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images } }
          - { name: alt, label: Alt text, type: string }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }

  # AUTHORS
  - name: authors
    label: Authors
    type: collection
    path: src/content/authors
    filename: "{year}{month}{day}-{hour}{minute}{second}.md"
    view:
      primary: name
      fields: [name, role]
      sort: [name]
    fields:
      - { name: name,  label: Name, type: string, required: true }
      - { name: role,  label: Role, type: string }
      - { name: bio,   label: Bio,  type: text }
      - name: image
        label: Image
        type: object
        fields:
          - { name: url, label: Image, type: image, options: { media: images } }
          - { name: alt, label: Alt text, type: string }
      - name: socials
        label: Socials
        type: object
        fields:
          - { name: twitter,  label: Twitter,  type: string }
          - { name: website,  label: Website,  type: string }
          - { name: linkedin, label: LinkedIn, type: string }
          - { name: email,    label: Email,    type: string }
      - { name: body, label: Body, type: rich-text }
